/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketRouteImport } from './routes/market'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as MarketIndexRouteImport } from './routes/market.index'
import { Route as PortfolioIncomeRouteImport } from './routes/portfolio.income'
import { Route as PortfolioContributionRouteImport } from './routes/portfolio.contribution'
import { Route as PortfolioAllocateRouteImport } from './routes/portfolio.allocate'
import { Route as PortfolioIdRouteImport } from './routes/portfolio.$id'
import { Route as MarketSearchRouteImport } from './routes/market.search'
import { Route as MarketScreenerRouteImport } from './routes/market.screener'
import { Route as MarketMacroRouteImport } from './routes/market.macro'
import { Route as MarketCompareRouteImport } from './routes/market.compare'
import { Route as MarketBenchmarksRouteImport } from './routes/market.benchmarks'
import { Route as ResearchTypeTickerRouteImport } from './routes/research.$type.$ticker'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketRoute,
} as any)
const PortfolioIncomeRoute = PortfolioIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioContributionRoute = PortfolioContributionRouteImport.update({
  id: '/contribution',
  path: '/contribution',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioAllocateRoute = PortfolioAllocateRouteImport.update({
  id: '/allocate',
  path: '/allocate',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioIdRoute = PortfolioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortfolioRoute,
} as any)
const MarketSearchRoute = MarketSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MarketRoute,
} as any)
const MarketScreenerRoute = MarketScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => MarketRoute,
} as any)
const MarketMacroRoute = MarketMacroRouteImport.update({
  id: '/macro',
  path: '/macro',
  getParentRoute: () => MarketRoute,
} as any)
const MarketCompareRoute = MarketCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => MarketRoute,
} as any)
const MarketBenchmarksRoute = MarketBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => MarketRoute,
} as any)
const ResearchTypeTickerRoute = ResearchTypeTickerRouteImport.update({
  id: '/research/$type/$ticker',
  path: '/research/$type/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/health': typeof HealthRoute
  '/journal': typeof JournalRoute
  '/market': typeof MarketRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/settings': typeof SettingsRoute
  '/validation': typeof ValidationRoute
  '/watchlist': typeof WatchlistRoute
  '/market/benchmarks': typeof MarketBenchmarksRoute
  '/market/compare': typeof MarketCompareRoute
  '/market/macro': typeof MarketMacroRoute
  '/market/screener': typeof MarketScreenerRoute
  '/market/search': typeof MarketSearchRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/allocate': typeof PortfolioAllocateRoute
  '/portfolio/contribution': typeof PortfolioContributionRoute
  '/portfolio/income': typeof PortfolioIncomeRoute
  '/market/': typeof MarketIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/research/$type/$ticker': typeof ResearchTypeTickerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/health': typeof HealthRoute
  '/journal': typeof JournalRoute
  '/settings': typeof SettingsRoute
  '/validation': typeof ValidationRoute
  '/watchlist': typeof WatchlistRoute
  '/market/benchmarks': typeof MarketBenchmarksRoute
  '/market/compare': typeof MarketCompareRoute
  '/market/macro': typeof MarketMacroRoute
  '/market/screener': typeof MarketScreenerRoute
  '/market/search': typeof MarketSearchRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/allocate': typeof PortfolioAllocateRoute
  '/portfolio/contribution': typeof PortfolioContributionRoute
  '/portfolio/income': typeof PortfolioIncomeRoute
  '/market': typeof MarketIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/research/$type/$ticker': typeof ResearchTypeTickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/health': typeof HealthRoute
  '/journal': typeof JournalRoute
  '/market': typeof MarketRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/settings': typeof SettingsRoute
  '/validation': typeof ValidationRoute
  '/watchlist': typeof WatchlistRoute
  '/market/benchmarks': typeof MarketBenchmarksRoute
  '/market/compare': typeof MarketCompareRoute
  '/market/macro': typeof MarketMacroRoute
  '/market/screener': typeof MarketScreenerRoute
  '/market/search': typeof MarketSearchRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/allocate': typeof PortfolioAllocateRoute
  '/portfolio/contribution': typeof PortfolioContributionRoute
  '/portfolio/income': typeof PortfolioIncomeRoute
  '/market/': typeof MarketIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/research/$type/$ticker': typeof ResearchTypeTickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/health'
    | '/journal'
    | '/market'
    | '/portfolio'
    | '/settings'
    | '/validation'
    | '/watchlist'
    | '/market/benchmarks'
    | '/market/compare'
    | '/market/macro'
    | '/market/screener'
    | '/market/search'
    | '/portfolio/$id'
    | '/portfolio/allocate'
    | '/portfolio/contribution'
    | '/portfolio/income'
    | '/market/'
    | '/portfolio/'
    | '/research/$type/$ticker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/health'
    | '/journal'
    | '/settings'
    | '/validation'
    | '/watchlist'
    | '/market/benchmarks'
    | '/market/compare'
    | '/market/macro'
    | '/market/screener'
    | '/market/search'
    | '/portfolio/$id'
    | '/portfolio/allocate'
    | '/portfolio/contribution'
    | '/portfolio/income'
    | '/market'
    | '/portfolio'
    | '/research/$type/$ticker'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/health'
    | '/journal'
    | '/market'
    | '/portfolio'
    | '/settings'
    | '/validation'
    | '/watchlist'
    | '/market/benchmarks'
    | '/market/compare'
    | '/market/macro'
    | '/market/screener'
    | '/market/search'
    | '/portfolio/$id'
    | '/portfolio/allocate'
    | '/portfolio/contribution'
    | '/portfolio/income'
    | '/market/'
    | '/portfolio/'
    | '/research/$type/$ticker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  HealthRoute: typeof HealthRoute
  JournalRoute: typeof JournalRoute
  MarketRoute: typeof MarketRouteWithChildren
  PortfolioRoute: typeof PortfolioRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ValidationRoute: typeof ValidationRoute
  WatchlistRoute: typeof WatchlistRoute
  ResearchTypeTickerRoute: typeof ResearchTypeTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/market/': {
      id: '/market/'
      path: '/'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof MarketRoute
    }
    '/portfolio/income': {
      id: '/portfolio/income'
      path: '/income'
      fullPath: '/portfolio/income'
      preLoaderRoute: typeof PortfolioIncomeRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/contribution': {
      id: '/portfolio/contribution'
      path: '/contribution'
      fullPath: '/portfolio/contribution'
      preLoaderRoute: typeof PortfolioContributionRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/allocate': {
      id: '/portfolio/allocate'
      path: '/allocate'
      fullPath: '/portfolio/allocate'
      preLoaderRoute: typeof PortfolioAllocateRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/market/search': {
      id: '/market/search'
      path: '/search'
      fullPath: '/market/search'
      preLoaderRoute: typeof MarketSearchRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/screener': {
      id: '/market/screener'
      path: '/screener'
      fullPath: '/market/screener'
      preLoaderRoute: typeof MarketScreenerRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/macro': {
      id: '/market/macro'
      path: '/macro'
      fullPath: '/market/macro'
      preLoaderRoute: typeof MarketMacroRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/compare': {
      id: '/market/compare'
      path: '/compare'
      fullPath: '/market/compare'
      preLoaderRoute: typeof MarketCompareRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/benchmarks': {
      id: '/market/benchmarks'
      path: '/benchmarks'
      fullPath: '/market/benchmarks'
      preLoaderRoute: typeof MarketBenchmarksRouteImport
      parentRoute: typeof MarketRoute
    }
    '/research/$type/$ticker': {
      id: '/research/$type/$ticker'
      path: '/research/$type/$ticker'
      fullPath: '/research/$type/$ticker'
      preLoaderRoute: typeof ResearchTypeTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketRouteChildren {
  MarketBenchmarksRoute: typeof MarketBenchmarksRoute
  MarketCompareRoute: typeof MarketCompareRoute
  MarketMacroRoute: typeof MarketMacroRoute
  MarketScreenerRoute: typeof MarketScreenerRoute
  MarketSearchRoute: typeof MarketSearchRoute
  MarketIndexRoute: typeof MarketIndexRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketBenchmarksRoute: MarketBenchmarksRoute,
  MarketCompareRoute: MarketCompareRoute,
  MarketMacroRoute: MarketMacroRoute,
  MarketScreenerRoute: MarketScreenerRoute,
  MarketSearchRoute: MarketSearchRoute,
  MarketIndexRoute: MarketIndexRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface PortfolioRouteChildren {
  PortfolioIdRoute: typeof PortfolioIdRoute
  PortfolioAllocateRoute: typeof PortfolioAllocateRoute
  PortfolioContributionRoute: typeof PortfolioContributionRoute
  PortfolioIncomeRoute: typeof PortfolioIncomeRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioIdRoute: PortfolioIdRoute,
  PortfolioAllocateRoute: PortfolioAllocateRoute,
  PortfolioContributionRoute: PortfolioContributionRoute,
  PortfolioIncomeRoute: PortfolioIncomeRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  HealthRoute: HealthRoute,
  JournalRoute: JournalRoute,
  MarketRoute: MarketRouteWithChildren,
  PortfolioRoute: PortfolioRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ValidationRoute: ValidationRoute,
  WatchlistRoute: WatchlistRoute,
  ResearchTypeTickerRoute: ResearchTypeTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
