/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketRouteImport } from './routes/market'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as MarketIndexRouteImport } from './routes/market.index'
import { Route as PortfolioContributionRouteImport } from './routes/portfolio.contribution'
import { Route as PortfolioIdRouteImport } from './routes/portfolio.$id'
import { Route as MarketSearchRouteImport } from './routes/market.search'
import { Route as MarketScreenerRouteImport } from './routes/market.screener'
import { Route as ResearchTypeTickerRouteImport } from './routes/research.$type.$ticker'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketRoute,
} as any)
const PortfolioContributionRoute = PortfolioContributionRouteImport.update({
  id: '/contribution',
  path: '/contribution',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioIdRoute = PortfolioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortfolioRoute,
} as any)
const MarketSearchRoute = MarketSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MarketRoute,
} as any)
const MarketScreenerRoute = MarketScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => MarketRoute,
} as any)
const ResearchTypeTickerRoute = ResearchTypeTickerRouteImport.update({
  id: '/research/$type/$ticker',
  path: '/research/$type/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/health': typeof HealthRoute
  '/market': typeof MarketRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/settings': typeof SettingsRoute
  '/market/screener': typeof MarketScreenerRoute
  '/market/search': typeof MarketSearchRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/contribution': typeof PortfolioContributionRoute
  '/market/': typeof MarketIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/research/$type/$ticker': typeof ResearchTypeTickerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/health': typeof HealthRoute
  '/settings': typeof SettingsRoute
  '/market/screener': typeof MarketScreenerRoute
  '/market/search': typeof MarketSearchRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/contribution': typeof PortfolioContributionRoute
  '/market': typeof MarketIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/research/$type/$ticker': typeof ResearchTypeTickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/health': typeof HealthRoute
  '/market': typeof MarketRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/settings': typeof SettingsRoute
  '/market/screener': typeof MarketScreenerRoute
  '/market/search': typeof MarketSearchRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/portfolio/contribution': typeof PortfolioContributionRoute
  '/market/': typeof MarketIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/research/$type/$ticker': typeof ResearchTypeTickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/health'
    | '/market'
    | '/portfolio'
    | '/settings'
    | '/market/screener'
    | '/market/search'
    | '/portfolio/$id'
    | '/portfolio/contribution'
    | '/market/'
    | '/portfolio/'
    | '/research/$type/$ticker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/health'
    | '/settings'
    | '/market/screener'
    | '/market/search'
    | '/portfolio/$id'
    | '/portfolio/contribution'
    | '/market'
    | '/portfolio'
    | '/research/$type/$ticker'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/health'
    | '/market'
    | '/portfolio'
    | '/settings'
    | '/market/screener'
    | '/market/search'
    | '/portfolio/$id'
    | '/portfolio/contribution'
    | '/market/'
    | '/portfolio/'
    | '/research/$type/$ticker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  HealthRoute: typeof HealthRoute
  MarketRoute: typeof MarketRouteWithChildren
  PortfolioRoute: typeof PortfolioRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ResearchTypeTickerRoute: typeof ResearchTypeTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/market/': {
      id: '/market/'
      path: '/'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof MarketRoute
    }
    '/portfolio/contribution': {
      id: '/portfolio/contribution'
      path: '/contribution'
      fullPath: '/portfolio/contribution'
      preLoaderRoute: typeof PortfolioContributionRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/market/search': {
      id: '/market/search'
      path: '/search'
      fullPath: '/market/search'
      preLoaderRoute: typeof MarketSearchRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/screener': {
      id: '/market/screener'
      path: '/screener'
      fullPath: '/market/screener'
      preLoaderRoute: typeof MarketScreenerRouteImport
      parentRoute: typeof MarketRoute
    }
    '/research/$type/$ticker': {
      id: '/research/$type/$ticker'
      path: '/research/$type/$ticker'
      fullPath: '/research/$type/$ticker'
      preLoaderRoute: typeof ResearchTypeTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketRouteChildren {
  MarketScreenerRoute: typeof MarketScreenerRoute
  MarketSearchRoute: typeof MarketSearchRoute
  MarketIndexRoute: typeof MarketIndexRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketScreenerRoute: MarketScreenerRoute,
  MarketSearchRoute: MarketSearchRoute,
  MarketIndexRoute: MarketIndexRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface PortfolioRouteChildren {
  PortfolioIdRoute: typeof PortfolioIdRoute
  PortfolioContributionRoute: typeof PortfolioContributionRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioIdRoute: PortfolioIdRoute,
  PortfolioContributionRoute: PortfolioContributionRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  HealthRoute: HealthRoute,
  MarketRoute: MarketRouteWithChildren,
  PortfolioRoute: PortfolioRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ResearchTypeTickerRoute: ResearchTypeTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
